server:
  port: 7007
spring:
  application:  #指定应用名称
    name: eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    hostname: localhost


