server:
  port: 7009
spring:
  application:
    name: eurake-server2
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone:
        http://server1:7000/eureka/
  instance:
    hostname: server2

